### ISSUE TITLE
AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by m-s-b** [inbux/ioBroker.drops-weather#6]
Hi, 

hab den Adapter gestern Abend mal installiert. Daten wurden einwandfrei abgerufen., ich kann allerdings nicht genau sagen wie oft. Hab heute früh mal reingeschaut und bekomme im 5 Minutentakt:
`AxiosError: Request failed with status code 500`
Hast du eine Idee woran das liegt?

**Comment by sigi2345** [comment]
> Hi,
> 
> hab den Adapter gestern Abend mal installiert. Daten wurden einwandfrei abgerufen., ich kann allerdings nicht genau sagen wie oft. Hab heute früh mal reingeschaut und bekomme im 5 Minutentakt: `AxiosError: Request failed with status code 500` Hast du eine Idee woran das liegt?

Bei mir auch.

**Comment by inbux** [comment]
Sttuscode 500 ist Internal Server Error -  das sind die üblichen Statuscodes, die man auch im Browser sehen kann. 
Wenn die Drops-Seite über einen Webbrowser erreichbar ist, sollte das eigentlich nicht kommen.

Ich habe mal die Log vom heutigen Tag bei mir durchgeschaut und konnte keinen Error 500 finden.
Es gab ab und zu einen "AxiosError: timeout of 5000ms exceeded"  - das kommt, wenn die Antwort vom Server länger als 5 Sekunden auf sich warten lässt (könnte man mal vergrößeren)

Der 5 Minuten Takt kommt durch das Abfrageintervall der Webseite.

**Comment by m-s-b** [comment]
Die Webseite war für mich aber durchgehend erreichbar. Den timeout Fehler hatte ich nur einmal. Adapter ist jetzt deaktiviert und ich schaue heute Abend noch Mal was er dann so treibt.

**Comment by sigi2345** [comment]
> Es gab ab und zu einen "AxiosError: timeout of 5000ms exceeded" - das kommt, wenn die Antwort vom Server länger als 5 Sekunden auf sich warten lässt (könnte man mal vergrößeren)

Würde ich vergrößern, aber lauft sehr gut. Arbeite gerade an einer Vis:

![Screenshot (5061)](https://user-images.githubusercontent.com/41079106/193402680-8771517a-61d5-4951-91c6-0a3705490ec7.png)

**Comment by inbux** [comment]
Ich habe mir den BarChart im Moment hinter meiner normalen Anzeige für die Temperatur gelegt:

![drops](https://user-images.githubusercontent.com/44289314/193404473-ee2f4ff1-5f7d-45ba-8459-975f3d59d39d.png)

Der Chart wird nur angezeigt, wenn "rainStartsAt" nicht gleich -1 ist.

**Comment by m-s-b** [comment]
@inbux 
Hab noch Mal getestet... Wenn ich einen Ort ohne Sonderzeichen im Namen nehme läuft der Adapter einwandfrei. Wenn ich einen Ort mit ö im Namen nehme kommt Fehler 500. Der kommt auch wenn ich ö durch oe ersetze. Wenn ich den Ort mit ö auf der Webseite eingebe ist das kein Problem. Komischerweise hat er beim ersten Abruf auch Daten geholt. Hast du ne Idee wie ich das ö maskieren kann?

**Comment by inbux** [comment]
du kannst auch die GPS Koordinaten eingeben, mit Komma getrennt - die
werden auf der Webseite normalerweise auch in der URL angezeigt
In der nächsten Version kann man auch alternativ automatisch die
Koordinaten aus der Systemkonfiguration benutzen.

Am Sa., 1. Okt. 2022 um 14:02 Uhr schrieb m-s-b ***@***.***>:

**Comment by sigi2345** [comment]
Hallo, sind auch mehrere Orte geplant? Oder eine Weitere Instanz anlegen.

**Comment by m-s-b** [comment]
@inbux 
Das mit den Koordinaten war mir nicht bekannt. Damit klappt es einwandfrei. Danke. Mit der Version 0.2 auch. Übernahme der Koordinaten aus den Systemeinstellungen ist ne gute Idee.  
Weitere Orte klingt interessant. Gerne ohne weitere Instanz.  
By the way... Kannst du einen Datenpunkt mit nur dem aktuellen Niederschlag einfügen? 
Und wenn du nen Thread unter Tester aufmachst kann ich hier zu machen ;-)

**Comment by inbux** [comment]
AktuellerNiederschlag ist jetzt drin.
Werde einen Beitrag unter Tester erstellen, sobald ich die Rechte dazu erhalten habe...
