### ISSUE TITLE
Vorhersage Text

### ISSUE THREAD

**Issue by chris76e** [inbux/ioBroker.drops-weather#60]
Erstmal danke für den schnelle fix. 
Ist es möglich den Text von hier als DP einzubinden? Wo jetzt steht "Es bleibt vorläufig Trocken"

![Screenshot 2024-02-05 134302](https://github.com/inbux/ioBroker.drops-weather/assets/81479633/bc108032-e121-4fb0-9a92-83298b84290c)

**Comment by inbux** [comment]
Habe ich mal testweise eingebunden
