### ISSUE TITLE
Werte anders aufbereitet

### ISSUE THREAD

**Issue by Trrw** [inbux/ioBroker.drops-weather#7]
Vielen Dank für diesen Adapter! Die Werte werden super abgeholt. Würde es möglich sein, die Regenwerte als eigene Datenpunkte auszugeben? Also ich meine jeweils einen Datenpunkt für die nächsten 5 Minuten und dort die Werte extrahiert:

"Datenpunkt" "Wert"
"0 Minuten" "0.1" mm/h
"5 Minuten" "0.1" mm/h
"10 Minuten" "0.3" mm/h
"15 Minuten" "0.5"mm/h

Vielen Dank!

**Comment by inbux** [comment]
Hallo,

damit man sich die Werte individuell aufbereiten kann, gibt es den Datenpunkt "raindata". Damit sollte man eigentlich alles leicht nach seinen Wünschen per Script machen können.
z.B.:

var raindata, element;

raindata = JSON.parse(getState("drops-weather.0.data_5min.raindata").val);
for (var element_index in raindata) {
  element = raindata[element_index];
  console.log(('Wert '  + String(element_index * 5) + "min = " + String(element)));
}


Damit kannst du dann auch dir beliebige eigene Datenpunkte mit den Werten erstellen...
